export const levels = [
  ['1. Forzantes o condicionantes climáticos','Cambios físicos, patrones o condiciones del clima que pueden modificar la ocurrencia o intensidad de otros procesos.','Aumento de temperatura, temperaturas extremas, precipitación intensa, variabilidad de la precipitación, periodos secos, sequía, humedad, radiación, viento, variabilidad climática y ENSO.'],
  ['2. Amenazas climáticas o socionaturales derivadas','Procesos potencialmente dañinos cuyo comportamiento está condicionado o amplificado por el clima y por características físicas o urbanas del territorio.','Inundaciones, anegamientos, crecientes súbitas, avenidas torrenciales, deslizamientos, erosión, incendios de cobertura vegetal, sequía hidrológica, déficit hídrico e isla de calor urbana.'],
  ['3. Efectos climáticamente sensibles','Fenómenos ambientales, sanitarios o sociales que no son amenazas climáticas primarias, pero cuya ocurrencia o severidad puede variar con las condiciones del clima.','Calidad del aire, estrés térmico, dengue y otros vectores, enfermedades transmitidas por agua, calidad del agua, estrés de la vegetación, biodiversidad y funciones ecosistémicas.'],
  ['4. Impactos territoriales y consecuencias en cascada','Consecuencias que se transmiten desde la amenaza hacia la población, los servicios, la infraestructura, la economía y otros sistemas urbanos.','Daños en viviendas e infraestructura, interrupción de acueducto, energía y transporte, aislamiento territorial, cadenas de abastecimiento, inseguridad alimentaria, precios, pérdidas económicas, desplazamiento y medios de vida.']
];

export const families = [
  ['1. Riesgos asociados al agua','Exceso de agua','Precipitación extrema, inundación pluvial y fluvial, anegamientos, crecientes súbitas, desbordamientos y avenidas torrenciales.'],
  ['1. Riesgos asociados al agua','Déficit de agua','Sequía meteorológica e hidrológica, reducción de caudales, déficit hídrico, disponibilidad de agua, demanda e interrupciones de abastecimiento.'],
  ['1. Riesgos asociados al agua','Calidad del agua','Turbiedad, contaminación por escorrentía, afectación de bocatomas, aumento de temperatura del agua y dificultades de tratamiento.'],
  ['2. Riesgos geohidrológicos','Inestabilidad de laderas','Deslizamientos, movimientos en masa, flujos de detritos, saturación, erosión y caída de rocas cuando exista relación con lluvia o variabilidad climática.'],
  ['3. Riesgos asociados al calor','Calor crónico','Aumento de temperatura media, isla de calor urbana, temperaturas nocturnas, pérdida de vegetación y acumulación térmica en viviendas y espacio público.'],
  ['3. Riesgos asociados al calor','Calor extremo','Días extremadamente cálidos, noches cálidas, episodios prolongados de calor, sensación térmica y estrés térmico.'],
  ['4. Incendios y sequedad','Incendios de cobertura vegetal','Periodos secos, temperatura, viento, humedad del combustible, ignición, propagación e incendios en la interfaz urbano-rural.'],
  ['5. Calidad del aire','Contaminación sensible al clima','PM2.5, PM10, ozono troposférico, humo de incendios, transporte de contaminantes, estabilidad atmosférica y episodios de baja dispersión.'],
  ['6. Salud sensible al clima','Enfermedades transmitidas por vectores','Dengue, chikunguña, zika, distribución y actividad de Aedes, temperatura, precipitación, humedad, agua almacenada y control vectorial.'],
  ['6. Salud sensible al clima','Otros efectos sanitarios','Enfermedades transmitidas por agua, zoonosis climáticamente sensibles y efectos respiratorios, cardiovasculares y ocupacionales asociados al calor.'],
  ['7. Riesgos para ecosistemas','Estrés ecosistémico','Estrés hídrico, mortalidad arbórea, incendios, erosión, fragmentación, biodiversidad y pérdida de regulación hídrica, térmica y atmosférica.'],
  ['8. Riesgos meteorológicos adicionales','Eventos atmosféricos','Vendavales, vientos fuertes, tormentas eléctricas, rayos y granizo. Mantenerlos como candidatos hasta verificar evidencia local suficiente.'],
  ['9. Seguridad alimentaria','Producción y disponibilidad','Pérdidas agrícolas, reducción de rendimientos, origen territorial de los alimentos, concentración de proveedores y dependencia externa.'],
  ['9. Seguridad alimentaria','Abastecimiento y logística','Cierres viales, afectación del transporte, centrales mayoristas, cadenas de frío, tiempos de viaje, pérdidas de productos e interrupciones de suministro.'],
  ['9. Seguridad alimentaria','Acceso económico','Precios mayoristas, IPC de alimentos, inflación, capacidad adquisitiva, sustitución de productos e inseguridad alimentaria de hogares vulnerables.'],
  ['10. Infraestructura y servicios urbanos','Servicios esenciales','Acueducto, energía, saneamiento, drenaje, atención de emergencias, salud, educación y continuidad operativa.'],
  ['10. Infraestructura y servicios urbanos','Movilidad y conectividad','Cierres viales, metro, metrocables, aeropuerto, aislamiento de barrios y corregimientos, logística regional y acceso a servicios.'],
  ['11. Riesgos económicos y sociales','Medios de vida y desigualdad','Pérdida de ingresos, suspensión de actividades, daños en comercio y vivienda, desplazamiento temporal, recuperación desigual y capacidad de respuesta.']
];

export const processes = [
  ['Precipitación extrema','Agua / Clima','Súbita o aguda','Intensidad + duración + humedad antecedente + topografía'],
  ['Variabilidad de la precipitación','Agua / Clima','Mixta','Estacionalidad + ENSO + distribución temporal y espacial'],
  ['Inundación pluvial o fluvial','Agua','Súbita o aguda','Precipitación + caudales + drenaje + impermeabilización'],
  ['Anegamiento urbano','Agua','Aguda y recurrente','Lluvia intensa + drenaje insuficiente + topografía local'],
  ['Creciente súbita','Agua','Súbita o aguda','Lluvia intensa aguas arriba + pendiente + respuesta de cuenca'],
  ['Avenida torrencial','Agua / Geohidrológico','Súbita o aguda','Lluvia + saturación + deslizamiento + sedimentos + pendiente'],
  ['Sequía meteorológica','Agua','Lenta o crónica','Déficit prolongado de precipitación + temperatura'],
  ['Sequía hidrológica','Agua','Lenta o crónica','Déficit de lluvia + reducción de caudales y almacenamiento'],
  ['Déficit hídrico','Agua / Servicios','Lenta o crónica','Sequía + demanda + almacenamiento + distribución'],
  ['Deterioro de la calidad del agua','Agua / Salud','Mixta','Escorrentía + sedimentos + contaminación + tratamiento'],
  ['Interrupción del abastecimiento de agua','Agua / Servicios','Mixta','Déficit o turbiedad + bocatomas + infraestructura + distribución'],
  ['Deslizamiento','Geohidrológico','Aguda con preparación progresiva','Lluvia antecedente + lluvia intensa + saturación + intervención'],
  ['Flujo de detritos','Geohidrológico','Súbita o aguda','Deslizamiento + agua + sedimentos + cauce + alta pendiente'],
  ['Erosión e inestabilidad progresiva','Geohidrológico','Lenta o mixta','Escorrentía + pérdida de cobertura + intervención del terreno'],
  ['Aumento de temperatura media','Calor','Lenta o crónica','Tendencia regional + urbanización + cobertura y morfología'],
  ['Isla de calor urbana','Calor','Lenta o crónica','Materiales + morfología + calor antropogénico + poca vegetación'],
  ['Temperaturas nocturnas elevadas','Calor / Salud','Mixta','Calor acumulado + baja ventilación + vivienda + humedad'],
  ['Calor extremo','Calor','Aguda o mixta','Temperatura regional + humedad + radiación + baja ventilación'],
  ['Estrés térmico','Calor / Salud','Aguda o mixta','Calor + humedad + radiación + actividad + vivienda'],
  ['Condiciones favorables para incendios','Incendios','Lenta o mixta','Periodo seco + calor + viento + humedad del combustible'],
  ['Incendio de cobertura vegetal','Incendios','Súbita o aguda','Combustible seco + ignición + viento + topografía'],
  ['PM2.5','Calidad del aire','Mixta','Emisiones + estabilidad + capa límite + topografía + incendios'],
  ['PM10','Calidad del aire','Mixta','Periodos secos + resuspensión + emisiones + viento y lluvia'],
  ['Ozono troposférico','Calidad del aire','Aguda o mixta','Temperatura + radiación + precursores + circulación atmosférica'],
  ['Episodio de baja dispersión','Calidad del aire','Aguda o mixta','Estabilidad + capa límite baja + viento débil + valle'],
  ['Actividad y distribución de vectores','Salud','Lenta o mixta','Temperatura + precipitación + humedad + agua almacenada'],
  ['Dengue y otras enfermedades vectoriales','Salud','Mixta','Vectores + clima + movilidad + condiciones sociales + control'],
  ['Enfermedades transmitidas por agua','Salud / Agua','Mixta','Calidad del agua + saneamiento + inundación + exposición'],
  ['Estrés hídrico de la vegetación','Ecosistemas','Lenta o crónica','Sequía + calor + evapotranspiración + suelo'],
  ['Deterioro de ecosistemas','Ecosistemas','Lenta o crónica','Calor + déficit hídrico + incendios + fragmentación'],
  ['Vendavales y vientos fuertes','Meteorológico','Súbita o aguda','Convección + tormenta + arbolado + infraestructura expuesta'],
  ['Tormentas eléctricas y rayos','Meteorológico','Súbita o aguda','Convección profunda + humedad + inestabilidad atmosférica'],
  ['Granizo','Meteorológico','Súbita o aguda','Convección intensa + corrientes ascendentes + inestabilidad'],
  ['Pérdida de producción alimentaria','Seguridad alimentaria','Mixta','Sequía o inundación + calor + plagas + daños en cultivos'],
  ['Interrupción del abastecimiento alimentario','Seguridad alimentaria','Aguda o mixta','Pérdidas agrícolas + cierres viales + logística + dependencia externa'],
  ['Incremento del precio de alimentos','Seguridad alimentaria','Lenta o mixta','Reducción de oferta + transporte + costos + inflación'],
  ['Reducción del acceso a alimentos','Seguridad alimentaria','Lenta o mixta','Precios + ingresos + disponibilidad + vulnerabilidad del hogar'],
  ['Interrupción de movilidad','Infraestructura y servicios','Aguda','Inundación o deslizamiento + vías + transporte público'],
  ['Interrupción de servicios esenciales','Infraestructura y servicios','Aguda o mixta','Amenaza física + redes expuestas + redundancia + capacidad operativa'],
  ['Daños en viviendas e infraestructura','Infraestructura y hábitat','Aguda o mixta','Amenaza + exposición + calidad constructiva + localización'],
  ['Pérdida de ingresos y medios de vida','Economía y sociedad','Mixta','Daños + interrupciones + empleo informal + capacidad de recuperación'],
  ['Desplazamiento temporal o permanente','Economía y sociedad','Mixta','Daño o riesgo no mitigable + evacuación + vivienda + redes sociales'],
  ['Evento compuesto','Multiamenaza','Aguda o mixta','Dos o más amenazas simultáneas o sucesivas'],
  ['Impacto en cascada','Multisistémico','Mixta','Amenaza inicial + fallas de servicios + propagación territorial']
];
