import fs from 'node:fs/promises';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const dir='outputs/01a089a5-63bb-7163-bf32-9b8c2e1100a4';
const w=Workbook.create();
const sheets=[
['Referencias de aporte','Observaciones preliminares de los textos','Apuntes de lectura somera. Aportes, disponibilidad de datos y confiabilidad pendientes de comprobar.',
['Texto identificado','Observación preliminar','Aporte posible / apartado','Qué revisar en el texto o sus datos','Uso previsto / precaución'],[
['Landslide timing and rainfall regimes in a rapidly urbanizing tropical mountain valley in Colombia — Aristizábal, Sanchez y Korup','El apunte inicial destaca la relación entre ENSO, régimen de lluvias y deslizamientos. Menciona un repositorio GitHub.','7.1 Clima y relieve; 8.5 Cuantificación de eventos','Localizar el repositorio; revisar variables, cobertura y licencia; examinar el inventario Geohazards; seleccionar figuras y evaluar su reproducción.','Posible fuente de registros históricos y perfiles territoriales. La valoración inicial de alta confiabilidad requiere revisión; un inventario no equivale a una zonificación de amenaza.'],
['The nocturnal boundary layer of Aburra’s valley, a tropical urban area with complex topography','El apunte inicial lo relaciona con la topografía y las condiciones atmosféricas nocturnas del valle.','7.1 Clima y relieve; conexión con 7.4 Calidad del aire','Comprobar variables analizadas y disponibilidad de datos; extraer mecanismos y resultados útiles.','Referencia explicativa para la redacción. Evaluar si permite elaborar una figura propia. Confiabilidad pendiente de revisión.'],
['Análisis de la influencia del diseño urbano en la meteorología del Valle de Aburrá','La lectura somera señala un análisis de lugares con mayor exposición térmica y su relación con el diseño urbano.','8.1 Amenazas climáticas relevantes; apoyo a 7.1','Revisar cómo obtiene las temperaturas; distinguir temperatura del aire y superficial; evaluar replicabilidad, datos y análisis por unidad político-administrativa.','Candidata para el análisis de isla de calor urbana y mapas térmicos. Robustez y condición de referencia principal por confirmar.'],
['Validation of the accuracy of the CHIRPS precipitation dataset at representing climate variability in a tropical mountainous region of South America','El apunte propone CHIRPS como complemento espacial para climatología regional y señala limitaciones a escala diaria.','7.1 Clima y relieve: precipitación','Verificar versión del producto, región, estaciones, periodo, métricas de validación y limitaciones documentadas.','Sustentar el alcance del uso de CHIRPS. Confirmar que los resultados del artículo aplican a la versión y escala elegidas.']],[55,48,32,60,60]],
['Mapas 7.1','Desarrollo visual y de contenido — 7.1','Fuentes y especificaciones tomadas del plan original; son opciones por verificar. “Por confirmar” indica información no registrada.',
['ID','Mapa / figura','Contenido que desarrolla','Opción local / oficial','Detalle y periodo local','Alternativa de procesamiento / GEE','Detalle y periodo alternativo','Limitación / comprobación','Próximo paso','Estado'],[
['M01','Relieve e hipsometría','Elevación, fondo de valle, laderas y divisorias.','DEM POT 2026, citado en el plan.','1 m indicado; metadatos y fecha por confirmar.','Copernicus DEM; el plan cita COPERNICUS/DEM/GLO30_2024_1.','30 m indicados; fecha y colección por verificar.','Comprobar tipo de modelo: terreno o superficie, y precisión.','Confirmar acceso y metadatos del DEM local; verificar alternativa.','Pendiente'],
['M02','Pendiente y orientación de laderas','Gradientes, exposición de laderas y condicionantes de escorrentía y clima.','Derivados del DEM POT 2026.','1 m indicado para el DEM; fecha por confirmar.','Derivados de Copernicus DEM.','30 m indicados para el DEM.','Documentar unidades de pendiente y método; revisar ruido de vegetación y edificaciones.','Seleccionar DEM y método de cálculo; definir escala de presentación.','Pendiente'],
['M03','Precipitación media anual y estacional','Distribución regional y ciclo anual de lluvias.','Ruta local aún no encontrada en el plan.','Por confirmar.','CHIRPS: el plan cita UCSB-CHC/CHIRPS/V3/DAILY_RNL.','0,05° (~5,6 km) indicados; periodo propuesto 1991–2020.','Confirmar colección y versión: la conversación también exploró Pentad. Definir uso y validación para la escala elegida.','Verificar producto, contrastar con estaciones disponibles y definir mapa y gráfico estacional.','Pendiente'],
['M04','Temperatura superficial','Contrastes térmicos entre superficies urbanas, vegetación, valle y laderas.','Ruta local aún no encontrada en el plan.','Por confirmar.','Landsat 8 y 9, Collection 2 Level 2.','~30 m de producto según el plan; periodo propuesto 2013–2025.','Distinguir tamaño de píxel y resolución térmica; separar LST de temperatura del aire; revisar nubosidad.','Revisar método del texto de diseño urbano y definir composiciones comparables.','Pendiente'],
['M05','Cobertura vegetal / condición biofísica','Vegetación, áreas construidas y relación con condiciones térmicas.','El plan cita DEM POT 2026; falta identificar una capa de coberturas.','Por confirmar.','Sentinel-2 SR Harmonized y NDVI; Dynamic World opcional.','10 m indicados; periodo propuesto 2017–2025.','El DEM citado no identifica por sí solo la cobertura requerida. Revisar máscaras de nubes y composición temporal.','Localizar cobertura oficial y decidir indicador o clasificación.','Pendiente'],
['M06','Relieve e hidrografía estructural','Divisorias, drenajes y relación relieve–agua.','DEM POT 2026 y POMCA, citados en el plan.','Resolución, fecha y red hídrica por confirmar.','DEM y MERIT/Hydro/v1_0_1, citado en el plan.','30–90 m indicados; verificar por capa.','Comprobar representación de quebradas urbanas y escala de la red.','Localizar red hídrica oficial y revisar compatibilidad con el DEM.','Pendiente']],[9,30,42,42,33,44,36,53,48,16]],
['Mapas 8.5','Desarrollo visual y de contenido — 8.5','Ideas de productos y rutas de datos. No se ha comprobado aquí la disponibilidad de las bases ni el avance de elaboración.',
['ID','Tema','Mapa / figura previsto','Contenido a desarrollar','Fuente / ruta por explorar','Datos y cobertura por comprobar','Tarea inmediata','Vacío / precaución','Estado'],[
['E01','Movimientos en masa','Mapa de eventos y línea temporal.','Distribución espacial y temporal del inventario.','Geohazards, citado en el plan.','Puntos; fechas, cobertura temporal, localización y atributos.','Revisar inventario, diccionario y disponibilidad de descarga.','Comprobar duplicados y cobertura antes de agregar por unidades territoriales.','Por confirmar'],
['E02','Precipitaciones extremas','Línea temporal; otras figuras por definir.','Relación entre registros de lluvia y episodios de interés.','GitHub del artículo de Aristizábal; estaciones en tierra; satélites para contraste.','Registros por estación, resolución temporal y periodo común.','Revisar el repositorio y localizar series; definir métricas y contraste temporal.','El plan propone revisar máximos mensuales si falla el detalle diario. Esa agregación no confirma por sí sola un extremo diario.','Por confirmar'],
['E03','Inundaciones','Línea temporal; mapa si hay localización suficiente.','Ocurrencia y distribución de eventos.','Buscar bases de datos; registros periodísticos como alternativa propuesta.','Fecha, lugar, tipo, afectaciones y fuente; periodo por definir.','Localizar catálogos y evaluar cobertura antes de completar con prensa.','Falta identificar base; conservar procedencia y posibles duplicados.','Por confirmar'],
['E04','Avenidas torrenciales','Línea temporal y mapa.','Eventos y cuencas o lugares afectados.','Comprobar si Geohazards las reporta.','Clasificación, fechas y localización; periodo por definir.','Revisar categorías y definición de los registros.','El plan pregunta por debris flow: verificar equivalencias antes de unificar categorías.','Por confirmar'],
['E05','Incendios','Por definir.','Contenido aún no desarrollado en el plan.','Sin fuente identificada.','Tipo de incendio, fecha, localización y extensión, según fuente.','Precisar alcance e identificar datos para decidir la figura.','No hay fuente, periodo ni producto definido en la tabla inicial.','Por definir'],
['E06','Picos de temperatura','Por definir.','Caracterización de episodios térmicos, por precisar.','Sin fuente identificada.','Variable de temperatura, frecuencia, periodo y criterio de pico.','Definir variable y localizar series antes de elegir la figura.','Distinguir temperatura del aire y superficial.','Por definir'],
['E07','Episodios de calidad del aire','Por definir.','Reportes de condiciones críticas y su posible relación meteorológica.','Reportes por localizar.','Contaminante o indicador, umbral, fecha y estación o territorio.','Definir alcance y articulación con 7.4 Calidad del aire.','Evaluar pertinencia en 8.5 y evitar duplicar el contenido de 7.4.','Por definir']],[9,28,35,43,49,49,52,55,17]]];
for(const [name,title,note,headers,rows,widths] of sheets){
 const s=w.worksheets.add(name);s.showGridLines=false;
 s.getRange('A2').values=[[title]];s.getRange('A3').values=[[note]];
 s.getRangeByIndexes(4,0,1,headers.length).values=[headers];
 s.getRangeByIndexes(5,0,rows.length,headers.length).values=rows;
 const area=s.getRangeByIndexes(4,0,rows.length+1,headers.length);
 area.format.font={name:'Arial',size:11,color:'#243447'};area.format.wrapText=true;area.format.verticalAlignment='top';
 s.getRangeByIndexes(4,0,1,headers.length).format={fill:'#24445C',font:{name:'Arial',size:11,bold:true,color:'#FFFFFF'},wrapText:true,rowHeight:34};
 s.getRange('A2').format.font={name:'Arial',size:16,bold:true,color:'#24445C'};
 s.getRange('A3').format.font={name:'Arial',size:10,italic:true,color:'#596675'};
 rows.forEach((_,i)=>{s.getRangeByIndexes(i+5,0,1,headers.length).format.rowHeight=name==='Referencias de aporte'?150:116;if(i%2===0)s.getRangeByIndexes(i+5,0,1,headers.length).format.fill='#EDF2F5';});
 widths.forEach((v,i)=>s.getRangeByIndexes(0,i,1,1).format.columnWidth=v);
 s.tables.add(area,true,'Tabla'+(w.worksheets.items.length));
 s.freezePanes.freezeRows(5);s.freezePanes.freezeColumns(name==='Referencias de aporte'?1:2);
}
w.recalculate();
for(const s of w.worksheets.items){const p=await w.render({sheetName:s.name,range:s.name==='Referencias de aporte'?'A1:E9':s.name==='Mapas 7.1'?'A1:J11':'A1:I12',scale:1,format:'png'});await fs.writeFile(`${dir}/corregida-${s.name}.png`,new Uint8Array(await p.arrayBuffer()));}
await(await SpreadsheetFile.exportXlsx(w)).save(`${dir}/Plan_de_ataque_corregido.xlsx`);
console.log((await w.inspect({kind:'workbook,sheet',maxChars:2000})).ndjson);
